version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ccd_db
      POSTGRES_USER: ccd_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ccd_db
      SPRING_DATASOURCE_USERNAME: ccd_user
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs

volumes:
  pgdata: