export const postTemplate = [{
        title: 'Post Title',
        description: 'Post Description',
        date: new Date('2023-10-01'),
        userId: '@UserID',
        userName: 'User Name',
        images:['image.png', 'image.png', 'image.png'],
    },
    {
        title: 'Post Title',
        description: 'Post Description',
        date: new Date('2023-10-01'),
        userId: '@UserID',
        userName: 'User Name',
    },
    {
        title: 'Post Title',
        description: 'Post Description',
        date: new Date('2023-10-01'),
        userId: '@UserID',
        userName: 'User Name',
        images:['image.png'],
    },
    {
        title: 'Post Title',
        description: 'Post Description',
        date: new Date('2023-10-01'),
        userId: '@UserID',
        userName: 'User Name',
        images:['image.png', 'image.png'],
    },
    {
        title: 'Post Title',
        description: 'Post Description',
        date: new Date('2023-10-01'),
        userId: '@UserID',
        userName: 'User Name',
        images:['image.png', 'image.png', 'image.png', 'image.png'],
    }
]