-- Table: users
CREATE TABLE users (
   id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_tag     VARCHAR(64) NOT NULL UNIQUE,
   full_name    VARCHAR(255),
   email        VARCHAR(255) NOT NULL UNIQUE,
   password     VARCHAR(255) NOT NULL,
   display_name VARCHAR(255),
   bio          TEXT,
   role         VARCHAR(20) DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN', 'SUPER_ADMIN')),
   created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   is_verified  BOOLEAN DEFAULT FALSE
);

-- Table: posts
CREATE TABLE posts (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id     BIGINT NOT NULL,
   title       VARCHAR(255),
   content     TEXT,
   created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Table: post_images
CREATE TABLE post_images (
         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         post_id    BIGINT NOT NULL,
         image_url  VARCHAR(512),
         created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
         CONSTRAINT fk_post_images_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

-- Table: likes
CREATE TABLE likes (
   user_id BIGINT NOT NULL,
   post_id BIGINT NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (user_id, post_id),
   CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users (id),
   CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

-- Table: comments
CREATE TABLE comments (
      id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      post_id    BIGINT NOT NULL,
      user_id    BIGINT NOT NULL,
      content    TEXT NOT NULL,
      created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id),
      CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Table: follows
CREATE TABLE follows (
     follower_id BIGINT NOT NULL,
     followee_id BIGINT NOT NULL,
     created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (follower_id, followee_id),
     CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id) REFERENCES users (id),
     CONSTRAINT fk_follows_followee FOREIGN KEY (followee_id) REFERENCES users (id)
);
