-- Table: users
CREATE TABLE users (
   id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_tag     VARCHAR(64) NOT NULL UNIQUE,
   email        VARCHAR(255) NOT NULL UNIQUE,
   password     VARCHAR(255) NOT NULL,
   display_name VARCHAR(255),
   role         VARCHAR(20) DEFAULT 'ROLE_USER' CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN')),
   is_private   BOOLEAN DEFAULT FALSE
);

-- Table: posts
CREATE TABLE posts (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id     BIGINT NOT NULL,
   title       VARCHAR(255),
   content     TEXT,
   created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Table: likes
CREATE TABLE likes (
   user_id BIGINT NOT NULL,
   post_id BIGINT NOT NULL,
   PRIMARY KEY (user_id, post_id),
   CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users (id),
   CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

-- Table: follows
CREATE TABLE follows (
     follower_id BIGINT NOT NULL,
     followee_id BIGINT NOT NULL,
     PRIMARY KEY (follower_id, followee_id),
     CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id) REFERENCES users (id),
     CONSTRAINT fk_follows_followee FOREIGN KEY (followee_id) REFERENCES users (id)
);
