spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ccd_db
    username: ccd_user
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validate-on-migrate: false
    baseline-on-migrate: true
    locations: classpath:db/migration
# Logs
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /concord
  port: 8080

cors:
  allowed-origin: http://localhost:4200, http://localhost:8080
  insecure: false
  postman-testing: true

jwt:
  secret: ykLx2aidrEhX6Jx58Je/Jg8/F7l/Jx2/RBosVlhgcVV6cZgIYHvLIzRTl4vI0SUs
  refresh-secret: x0OStMBKJVX+Fk3yvL9HIqNIpAoqyIYpbvAjRuQTw5xlJbMtSsDmy4xI63xsiB3f
  token-duration: 1800               # default: 30 min
  refresh-token-duration: 2592000    # default: 1 month
  issuer: concord
